### ISSUE TITLE
Typo in the `packages.yml` example

### ISSUE THREAD

**Issue by b-per** [AxelThevenot/dbt-assertions#18]
The example shows `version: [">=1.0.0", "<2.0.0"]` but this should be `version: [">=0.1.0", "<0.2.0"]` based on the current version

**Comment by AxelThevenot** [comment]
Yes sorry, this is because I will make a breaking change during the weekend
I have two prereleases https://github.com/AxelThevenot/dbt-assertions/releases
I will be ok on monday :)
