### ISSUE TITLE
Consider using `column: meta: assertions` rather than `column: assertions`

### ISSUE THREAD

**Issue by b-per** [AxelThevenot/dbt-assertions#20]
I was chatting with some colleagues and I was wondering if the assertions would show in `manifest.json` if they are not under [`meta`](https://docs.getdbt.com/reference/resource-configs/meta). 

Putting them under `meta` would also make them show in the docs I believe.

**Comment by AxelThevenot** [comment]
Yes they are

And I will make a script to parse it before generating docs

**Comment by AxelThevenot** [comment]
But good idea if it is shown in the docs, I check that

**Comment by AxelThevenot** [comment]
I can not import the screen Github isn't working as expected now but I tried it and it imports the meta as a raw JSON string.
Not really informative to my point of view 

I prefer to stay clean in the code without the `meta` tag

Then create as I planned a littre script to integrate during the CI/CD as written here https://github.com/AxelThevenot/dbt-assertions/issues/9

**Comment by AxelThevenot** [comment]
I already made a draft of this script and it works, I will improve it later :), but thank you for the idea!
