### ISSUE TITLE
Add integration tests to facilitate adding support for new adapters

### ISSUE THREAD

**Issue by b-per** [AxelThevenot/dbt-assertions#24]
It would be great if the package included some integration tests, like in dbt_project_evaluator for example: https://github.com/dbt-labs/dbt-project-evaluator/tree/main/integration_tests

While it would be awesome to have those tests run in a CI/CD pipeline, before that, having tests defined would allow more people to contribute, making sure that their implementation is working.

The way it works in dbt_project_evaluator is that the folder is a dbt project itself, that installs the package from `..` and people can then `cd` to the project and do a `dbt build`, which run models and also tests that the output of those models matches some predefined seeds.

**Comment by AxelThevenot** [comment]
https://github.com/AxelThevenot/dbt-assertions/pull/29
